bindAddr: :4000
mailCheckerURL: http://apilayer.net/api/check?access_key=%s&smtp=1&format=&email=
mongo:
  uri: mongodb://mongo_user:mongo_secret@localhost:27017
  collection:
    name: subscriptions
  database:
    name: goEchoBasics